#include "port_vga.h"
#include "port_memory.h"
#include "scalers2x.h"

extern "C" void PortWatchdog_Ping(void);
// Emulace preruseni od myshi - viz komentar v Present() a port_dos.cpp.
extern "C" void PortDos_ServiceMouse(void);
#include "port_sound.h"

#include <SDL3/SDL.h>
#include <array>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

extern "C" void PortCtl_Tick();   /* vlna 112: srovnavaci harness (port_ctl.cpp) */

namespace Port::Vga {

    namespace {
        // Vlna 21: 640x480 - hra bezi ve vynucenem VESA modu 5 (viz sub_1248AB).
        constexpr int kModeWidth = 640;
        constexpr int kModeHeight = 480;

        // Zaloha = 5 celych VESA bank po 64 KiB (327680 B > 640*480 = 307200 B):
        // bankovane kopie originalu (sub_1255DF, sub_125814...) smely sahat az na
        // konec posledniho 64KiB okna, ne jen na konec viditelneho obrazu.
        constexpr size_t kFramebufferBytes = 5 * 0x10000;

        SDL_Window* g_window = nullptr;
        SDL_Renderer* g_renderer = nullptr;
        SDL_Texture* g_texture = nullptr;        // 1280x960 - vystup CPU 2x algoritmu (vse krome nearest/bilinear)
        SDL_Texture* g_textureNative = nullptr;  // 640x480 - primy upload pro nearest/bilinear, GPU si samo dela roztazeni

        // 640x480 source converted through the VGA palette to ARGB8888.
        std::vector<uint32_t> g_argbFramebuffer;

        // 1280x960 output generated by the selected 2x scaler.
        std::vector<uint32_t> g_scaledFramebuffer;

        // Framebuffer NENI staticke pole. Dekompilovany kod ho uklada do 32bit intu
        // (dword_1BB910[0] = (int)PortVga_Framebuffer()); staticke pole zije v datovem
        // segmentu modulu, ktery na x64 lezi vysoko (image base ~0x140000000) - cast
        // na int ho orezal na 0/garbage (odtud hlaseny "result=0" v sub_138CE0).
        // Proto ho bereme z HALDY pres malloc: pod /LARGEADDRESSAWARE:NO lezi heap v
        // dolnich 2 GB a ukazatel round-tripuje pres int - stejne jako vsechny ostatni
        // buffery portu (dword_1BB90C z PoolAlloc funguje presne z tohoto duvodu).
        uint8_t* g_framebuffer = nullptr;

        std::array<uint32_t, 256> g_palette{}; // ulozeno uz jako ARGB8888 pro SDL

        bool g_initialized = false;

        // Debug-only frame dump, requested by user to compare the port's actual
        // rendered framebuffer+palette against dosbox-x DUMPFRAME captures of the
        // original, byte-for-byte, instead of relying on register-trace inference
        // alone.
        //
        // Two modes, both read once from env on first call:
        //
        //   REORION2_DUMP_FRAME=N
        //       legacy single dump at Present() #N,
        //       writes port_frame.raw + port_frame.bmp.
        //
        //   REORION2_DUMP_FRAME_RANGE=S:C
        //       batch dump of C consecutive frames starting at Present() #S,
        //       writes frame_00000.raw .. frame_(C-1).raw.
        //
        // SAME layout as dosbox-x's DUMPFRAME:
        //   768B RGB8 palette + WxH index bytes
        //
        // Both write to REORION2_DUMP_DIR (default: cwd).
        void DumpRawFrame(const std::string& path,
            const uint8_t* framebuffer,
            const std::array<uint32_t, 256>& palette,
            int width,
            int height)
        {
            FILE* f = std::fopen(path.c_str(), "wb");
            if (!f)
                return;

            for (int i = 0; i < 256; ++i) {
                uint32_t argb = palette[static_cast<size_t>(i)];

                uint8_t rgb[3] = {
                    static_cast<uint8_t>((argb >> 16) & 0xFF),
                    static_cast<uint8_t>((argb >> 8) & 0xFF),
                    static_cast<uint8_t>(argb & 0xFF)
                };

                std::fwrite(rgb, 1, 3, f);
            }

            std::fwrite(framebuffer, 1,
                static_cast<size_t>(width) * height,
                f);

            std::fclose(f);
        }

        unsigned char expand6to8(unsigned char v)
        {
            return static_cast<unsigned char>((v << 2) | (v >> 4));
        }

        static bool FramesRoughlyMatch(
            const std::vector<uint8_t>& ref,
            const uint8_t* fb,
            const std::array<uint32_t, 256>& pal,
            size_t fbBytes,
            int* outPaletteMismatches,
            long* outPixelMismatches,
            long* outFirstPixelMismatch)
        {
            int paletteMismatches = 0;

            for (int c = 0; c < 256 * 3; ++c) {
                uint8_t refVal =
                    expand6to8(ref[static_cast<size_t>(c)]);

                int ch = c % 3;
                uint32_t argb =
                    pal[static_cast<size_t>(c / 3)];

                uint8_t portVal =
                    (ch == 0)
                    ? static_cast<uint8_t>((argb >> 16) & 0xFF)
                    : (ch == 1)
                    ? static_cast<uint8_t>((argb >> 8) & 0xFF)
                    : static_cast<uint8_t>(argb & 0xFF);

                if (refVal != portVal)
                    ++paletteMismatches;
            }

            long firstPixelMismatch = -1;
            long pixelMismatches = 0;

            for (size_t px = 0; px < fbBytes; ++px) {
                if (ref[768 + px] != fb[px]) {
                    if (firstPixelMismatch < 0)
                        firstPixelMismatch =
                        static_cast<long>(px);

                    ++pixelMismatches;
                }
            }

            if (outPaletteMismatches)
                *outPaletteMismatches = paletteMismatches;

            if (outPixelMismatches)
                *outPixelMismatches = pixelMismatches;

            if (outFirstPixelMismatch)
                *outFirstPixelMismatch = firstPixelMismatch;

            return paletteMismatches == 0 &&
                pixelMismatches == 0;
        }

        void CompareAgainstReferenceIfChanged(
            const uint8_t* framebuffer,
            const std::array<uint32_t, 256>& palette,
            int width,
            int height)
        {
            constexpr int kMaxExtraFrames = 300;

            static bool s_enabled = false;
            static bool s_checked = false;

            static std::string s_dir;

            static int s_refIndex = 0;
            static int s_skipCount = 0;

            static int s_extraFramesSinceLastMatch = 0;
            static int s_totalPortFrames = 0;

            static std::vector<uint8_t> s_lastFb;
            static std::array<uint32_t, 256> s_lastPal{};

            static bool s_havePrev = false;

            if (!s_checked) {
                s_checked = true;

                if (const char* env =
                    std::getenv("REORION2_COMPARE_DIR")) {

                    s_dir = env;
                    s_enabled = true;

                    if (const char* skipEnv =
                        std::getenv("REORION2_COMPARE_SKIP")) {

                        s_skipCount = std::atoi(skipEnv);
                    }

                    s_refIndex = s_skipCount;

                    SDL_Log(
                        "Port::Vga: comparing against dosbox reference frames in %s "
                        "(starting at ref #%d)",
                        s_dir.c_str(),
                        s_refIndex);
                }
            }

            if (!s_enabled)
                return;

            static bool s_paletteGate =
                std::getenv("REORION2_DUMP_INCLUDE_PALETTE") != nullptr;

            size_t fbBytes =
                static_cast<size_t>(width) * height;

            bool pixelChanged =
                !s_havePrev ||
                s_lastFb.size() != fbBytes ||
                std::memcmp(
                    s_lastFb.data(),
                    framebuffer,
                    fbBytes) != 0;

            bool paletteChanged =
                s_paletteGate &&
                (!s_havePrev || s_lastPal != palette);

            bool changed =
                pixelChanged || paletteChanged;

            if (!changed) {
                s_lastPal = palette;
                return;
            }

            s_lastFb.assign(
                framebuffer,
                framebuffer + fbBytes);

            s_lastPal = palette;
            s_havePrev = true;

            ++s_totalPortFrames;

            char path[1024];

            std::snprintf(
                path,
                sizeof(path),
                "%s/frame_%05d.raw",
                s_dir.c_str(),
                s_refIndex);

            FILE* f = std::fopen(path, "rb");

            if (!f) {
                SDL_Log(
                    "Port::Vga: no more reference frames at %s "
                    "- comparison finished "
                    "(reached ref #%d, %d port frames total)",
                    path,
                    s_refIndex,
                    s_totalPortFrames);

                s_enabled = false;
                return;
            }

            std::vector<uint8_t> ref(
                768 + fbBytes);

            size_t got =
                std::fread(
                    ref.data(),
                    1,
                    ref.size(),
                    f);

            std::fclose(f);

            if (got != ref.size()) {
                SDL_Log(
                    "Port::Vga: reference frame %s has wrong size "
                    "(%zu, expected %zu) - stopping comparison",
                    path,
                    got,
                    ref.size());

                s_enabled = false;
                return;
            }

            int paletteMismatches = 0;
            long pixelMismatches = 0;
            long firstPixelMismatch = -1;

            bool matches =
                FramesRoughlyMatch(
                    ref,
                    framebuffer,
                    palette,
                    fbBytes,
                    &paletteMismatches,
                    &pixelMismatches,
                    &firstPixelMismatch);

            if (matches) {
                SDL_Log(
                    "Port::Vga: port frame #%d MATCHES reference #%d "
                    "(%d extra port frame(s) before this match).",
                    s_totalPortFrames,
                    s_refIndex,
                    s_extraFramesSinceLastMatch);

                ++s_refIndex;
                s_extraFramesSinceLastMatch = 0;
                return;
            }

            ++s_extraFramesSinceLastMatch;

            if (s_extraFramesSinceLastMatch <= kMaxExtraFrames) {
                SDL_Log(
                    "Port::Vga: port frame #%d does not match reference #%d yet "
                    "(%d/%d tolerated extra frame(s)) - "
                    "palette_mismatches=%d pixel_mismatches=%ld",
                    s_totalPortFrames,
                    s_refIndex,
                    s_extraFramesSinceLastMatch,
                    kMaxExtraFrames,
                    paletteMismatches,
                    pixelMismatches);

                return;
            }

            SDL_Log(
                "=== GENUINE DIVERGENCE: "
                "port frame #%d never reached reference #%d "
                "after %d extra frame(s) ===",
                s_totalPortFrames,
                s_refIndex,
                s_extraFramesSinceLastMatch);

            SDL_Log(
                "  reference file: %s",
                path);

            SDL_Log(
                "  palette channel mismatches: %d/768",
                paletteMismatches);

            SDL_Log(
                "  pixel mismatches: %ld/%zu "
                "(first at x=%ld y=%ld)",
                pixelMismatches,
                fbBytes,
                firstPixelMismatch < 0
                ? -1
                : firstPixelMismatch % width,
                firstPixelMismatch < 0
                ? -1
                : firstPixelMismatch / width);

            SDL_Log(
                "Port::Vga: aborting - see log above.");

            std::fflush(nullptr);
            std::exit(3);
        }

        void DumpFrameIfRequested(
            const uint8_t* framebuffer,
            const std::array<uint32_t, 256>& palette,
            int width,
            int height)
        {
            static int s_presentCount = 0;
            ++s_presentCount;

            PortCtl_Tick();

            const char* dir =
                std::getenv("REORION2_DUMP_DIR");

            std::string base =
                dir ? dir : ".";

            static int s_rangeStart = -2;
            static int s_rangeCount = 0;

            static std::vector<uint8_t> s_lastFb;
            static std::array<uint32_t, 256> s_lastPal{};

            static bool s_havePrev = false;
            static int s_distinctWritten = 0;

            if (s_rangeStart == -2) {
                s_rangeStart = -1;

                if (const char* env =
                    std::getenv("REORION2_DUMP_FRAME_RANGE")) {

                    int start = -1;
                    int count = 0;

                    if (std::sscanf(
                        env,
                        "%d:%d",
                        &start,
                        &count) == 2 &&
                        start > 0 &&
                        count > 0) {

                        s_rangeStart = start;
                        s_rangeCount = count;
                    }
                }
            }

            static Uint64 s_afterMs =
                0xFFFFFFFFULL;

            if (s_afterMs == 0xFFFFFFFFULL) {
                const char* env =
                    std::getenv("REORION2_DUMP_AFTER_MS");

                s_afterMs =
                    env
                    ? static_cast<Uint64>(std::atoi(env))
                    : 0;
            }

            if (SDL_GetTicks() < s_afterMs)
                return;

            if (s_rangeStart > 0 &&
                s_presentCount >= s_rangeStart &&
                s_distinctWritten < s_rangeCount) {

                static bool s_paletteGate =
                    std::getenv(
                        "REORION2_DUMP_INCLUDE_PALETTE") != nullptr;

                size_t fbBytes =
                    static_cast<size_t>(width) * height;

                bool pixelChanged =
                    !s_havePrev ||
                    s_lastFb.size() != fbBytes ||
                    std::memcmp(
                        s_lastFb.data(),
                        framebuffer,
                        fbBytes) != 0;

                bool paletteChanged =
                    s_paletteGate &&
                    (!s_havePrev || s_lastPal != palette);

                bool changed =
                    pixelChanged ||
                    paletteChanged;

                if (changed) {
                    char name[64];

                    std::snprintf(
                        name,
                        sizeof(name),
                        "/frame_%05d.raw",
                        s_distinctWritten);

                    DumpRawFrame(
                        base + name,
                        framebuffer,
                        palette,
                        width,
                        height);

                    SDL_Log(
                        "Port::Vga: batch frame #%d "
                        "(Present #%d, t=%llu ms, distinct draw) "
                        "dumped to %s%s",
                        s_distinctWritten,
                        s_presentCount,
                        static_cast<unsigned long long>(
                            SDL_GetTicks()),
                        base.c_str(),
                        name);

                    s_lastFb.assign(
                        framebuffer,
                        framebuffer + fbBytes);

                    s_lastPal = palette;
                    s_havePrev = true;

                    ++s_distinctWritten;
                }
            }

            static int s_target = -2;

            if (s_target == -2) {
                const char* env =
                    std::getenv("REORION2_DUMP_FRAME");

                s_target =
                    env
                    ? std::atoi(env)
                    : -1;
            }

            if (s_target <= 0 ||
                s_presentCount != s_target)
                return;

            std::string rawPath =
                base + "/port_frame.raw";

            std::string bmpPath =
                base + "/port_frame.bmp";

            DumpRawFrame(
                rawPath,
                framebuffer,
                palette,
                width,
                height);

            SDL_Log(
                "Port::Vga: frame #%d dumped to %s "
                "(palette+%dx%d indices)",
                s_presentCount,
                rawPath.c_str(),
                width,
                height);

            if (FILE* f =
                std::fopen(bmpPath.c_str(), "wb")) {

                int rowSize =
                    ((width * 3 + 3) / 4) * 4;

                uint32_t pixelDataSize =
                    static_cast<uint32_t>(rowSize) *
                    static_cast<uint32_t>(height);

                uint32_t fileSize =
                    54 + pixelDataSize;

                uint8_t header[54] = { 0 };

                header[0] = 'B';
                header[1] = 'M';

                std::memcpy(
                    &header[2],
                    &fileSize,
                    4);

                uint32_t dataOffset = 54;

                std::memcpy(
                    &header[10],
                    &dataOffset,
                    4);

                uint32_t dibSize = 40;

                std::memcpy(
                    &header[14],
                    &dibSize,
                    4);

                int32_t w32 = width;
                int32_t h32 = height;

                std::memcpy(
                    &header[18],
                    &w32,
                    4);

                std::memcpy(
                    &header[22],
                    &h32,
                    4);

                uint16_t planes = 1;
                uint16_t bpp = 24;

                std::memcpy(
                    &header[26],
                    &planes,
                    2);

                std::memcpy(
                    &header[28],
                    &bpp,
                    2);

                std::memcpy(
                    &header[34],
                    &pixelDataSize,
                    4);

                std::fwrite(
                    header,
                    1,
                    54,
                    f);

                std::vector<uint8_t> row(
                    static_cast<size_t>(rowSize),
                    0);

                for (int y = height - 1;
                    y >= 0;
                    --y) {

                    for (int x = 0;
                        x < width;
                        ++x) {

                        uint32_t argb =
                            palette[
                                framebuffer[
                                    static_cast<size_t>(y) * width + x]];

                        row[
                            static_cast<size_t>(x) * 3 + 0] =
                            static_cast<uint8_t>(
                                argb & 0xFF);

                            row[
                                static_cast<size_t>(x) * 3 + 1] =
                                static_cast<uint8_t>(
                                    (argb >> 8) & 0xFF);

                                row[
                                    static_cast<size_t>(x) * 3 + 2] =
                                    static_cast<uint8_t>(
                                        (argb >> 16) & 0xFF);
                    }

                    std::fwrite(
                        row.data(),
                        1,
                        static_cast<size_t>(rowSize),
                        f);
                }

                std::fclose(f);

                SDL_Log(
                    "Port::Vga: frame #%d dumped to %s",
                    s_presentCount,
                    bmpPath.c_str());
            }
        }

        uint8_t* EnsureFramebuffer()
        {
            if (g_framebuffer)
                return g_framebuffer;

            g_framebuffer =
                static_cast<uint8_t*>(
                    std::calloc(
                        kFramebufferBytes,
                        1));

            if (!g_framebuffer) {
                SDL_Log(
                    "Port::Vga: calloc framebufferu (%zu B) selhal",
                    kFramebufferBytes);

                return nullptr;
            }

            auto asInt =
                static_cast<uintptr_t>(
                    reinterpret_cast<uintptr_t>(
                        g_framebuffer));

            if (asInt > 0x7FFFFFFFu) {
                SDL_Log(
                    "Port::Vga: VAROVANI - framebuffer na %p "
                    "NEsedi do 32bit intu!",
                    static_cast<void*>(
                        g_framebuffer));
            }

            return g_framebuffer;
        }

        // ------------------------------------------------------------
        // Vyber 2x scaleru. Kazdy algoritmus ma PRAVE JEDEN kanonicky
        // nazev pro REORION2_SCALER (zadne matouci aliasy typu "eagle"
        // pro SuperEagle nebo "supersai" pro Super2xSaI - pokud dva
        // nazvy oznacuji uplne stejny kod, je to jen jeden algoritmus
        // s jednim nazvem).
        //
        //   nearest        - Scalers2x::Normal2x
        //   bilinear       - Scalers2x::Interpolation2x
        //   scale2x        - Scalers2x::AdvMame2x (aka EPX)
        //   sai2x          - Scalers2x::SAI2x (2xSaI)
        //   super2xsai     - Scalers2x::Super2xSaI
        //   supereagle     - Scalers2x::SuperEagle2x (DEFAULT)
        //   hq2xlite       - Scalers2x::Hq2xLite (prahova rovnost per-kanal
        //                     RGB; REORION2_HQ2XLITE_THRESHOLD, default 24)
        //   hq2xfull       - Scalers2x::Hq2xFull (prahova rovnost v YUV,
        //                     oddeleny prah pro jas/barvu - blize
        //                     originalnimu HQ2x nez hq2xlite;
        //                     REORION2_HQ2XFULL_Y_THRESHOLD, default 48;
        //                     REORION2_HQ2XFULL_U_THRESHOLD, default 7;
        //                     REORION2_HQ2XFULL_V_THRESHOLD, default 6)
        //   scale2xsmooth  - Scalers2x::Scale2xSmooth (graded Scale2x,
        //                     prah je pevny v kodu, viz kScale2xSmoothThreshold)
        // ------------------------------------------------------------
        enum class ScalerKind {
            Nearest = 0,
            Bilinear,
            Scale2x,
            Sai2x,
            Super2xSai,
            SuperEagle,
            Hq2xLite,
            Hq2xFull,
            Scale2xSmooth,
        };

        const char* ScalerName(ScalerKind k)
        {
            switch (k) {
            case ScalerKind::Nearest:       return "nearest";
            case ScalerKind::Bilinear:      return "bilinear";
            case ScalerKind::Scale2x:       return "scale2x";
            case ScalerKind::Sai2x:         return "sai2x";
            case ScalerKind::Super2xSai:    return "super2xsai";
            case ScalerKind::SuperEagle:    return "supereagle";
            case ScalerKind::Hq2xLite:      return "hq2xlite";
            case ScalerKind::Hq2xFull:      return "hq2xfull";
            case ScalerKind::Scale2xSmooth: return "scale2xsmooth";
            }
            return "supereagle";
        }

        ScalerKind ParseScalerKind(const char* env)
        {
            // Default: SuperEagle.
            if (!env)
                return ScalerKind::Bilinear;

            if (SDL_strcasecmp(env, "nearest") == 0)
                return ScalerKind::Nearest;
            if (SDL_strcasecmp(env, "bilinear") == 0)
                return ScalerKind::Bilinear;
            if (SDL_strcasecmp(env, "scale2x") == 0)
                return ScalerKind::Scale2x;
            if (SDL_strcasecmp(env, "sai2x") == 0)
                return ScalerKind::Sai2x;
            if (SDL_strcasecmp(env, "super2xsai") == 0)
                return ScalerKind::Super2xSai;
            if (SDL_strcasecmp(env, "supereagle") == 0)
                return ScalerKind::SuperEagle;
            if (SDL_strcasecmp(env, "hq2xlite") == 0)
                return ScalerKind::Hq2xLite;
            if (SDL_strcasecmp(env, "hq2xfull") == 0)
                return ScalerKind::Hq2xFull;
            if (SDL_strcasecmp(env, "scale2xsmooth") == 0)
                return ScalerKind::Scale2xSmooth;

            SDL_Log(
                "PortVga: unknown REORION2_SCALER='%s', using supereagle",
                env);
            return ScalerKind::SuperEagle;
        }

        // Scale2xSmooth: prah je zamerne pevny (bez env promenne) - viz
        // pozadavek uzivatele. Uprav primo tady, pokud potrebujes doladit.
        constexpr int kScale2xSmoothThreshold = 32;

    } // namespace

    uint8_t* Framebuffer()
    {
        return EnsureFramebuffer();
    }

    bool Init()
    {
        if (g_initialized)
            return true;

        if (!SDL_Init(SDL_INIT_VIDEO)) {
            SDL_Log(
                "Port::Vga::Init - SDL_Init selhalo: %s",
                SDL_GetError());

            return false;
        }

        g_window =
            SDL_CreateWindow(
                "Orion",
                kModeWidth * 2,
                kModeHeight * 2,
                0);

        if (!g_window) {
            SDL_Log(
                "Port::Vga::Init - SDL_CreateWindow selhalo: %s",
                SDL_GetError());

            return false;
        }

        g_renderer =
            SDL_CreateRenderer(
                g_window,
                nullptr);

        if (!g_renderer) {
            SDL_Log(
                "Port::Vga::Init - SDL_CreateRenderer selhalo: %s",
                SDL_GetError());

            return false;
        }

        // The scaler always produces a 2x image:
        // 640x480 -> 1280x960. NEAREST scale mode, aby pripadne dalsi
        // GPU roztazeni (kdyby okno bylo vetsi nez presne 2x) nerozmazalo
        // uz hotovy vystup algoritmu.
        g_texture =
            SDL_CreateTexture(
                g_renderer,
                SDL_PIXELFORMAT_ARGB8888,
                SDL_TEXTUREACCESS_STREAMING,
                kModeWidth * 2,
                kModeHeight * 2);

        if (!g_texture) {
            SDL_Log(
                "Port::Vga::Init - SDL_CreateTexture selhalo: %s",
                SDL_GetError());

            return false;
        }

        SDL_SetTextureScaleMode(
            g_texture,
            SDL_SCALEMODE_NEAREST);

        // Nativni 640x480 textura pro "nearest"/"bilinear" - zadny CPU
        // 2x pass, roztazeni na velikost okna dela primo GPU pri
        // vykresleni (scale mode se nastavuje az podle vybraneho
        // scaleru, viz Present()).
        g_textureNative =
            SDL_CreateTexture(
                g_renderer,
                SDL_PIXELFORMAT_ARGB8888,
                SDL_TEXTUREACCESS_STREAMING,
                kModeWidth,
                kModeHeight);

        if (!g_textureNative) {
            SDL_Log(
                "Port::Vga::Init - SDL_CreateTexture (native) selhalo: %s",
                SDL_GetError());

            return false;
        }

        EnsureFramebuffer();

        const size_t sourcePixels =
            static_cast<size_t>(kModeWidth) *
            kModeHeight;

        const size_t scaledPixels =
            static_cast<size_t>(kModeWidth * 2) *
            (kModeHeight * 2);

        g_argbFramebuffer.resize(
            sourcePixels);

        g_scaledFramebuffer.resize(
            scaledPixels);

        g_palette.fill(
            0xFF000000u);

        SDL_HideCursor();

        g_initialized = true;

        return true;
    }

    void Shutdown()
    {
        if (g_texture) {
            SDL_DestroyTexture(g_texture);
            g_texture = nullptr;
        }

        if (g_textureNative) {
            SDL_DestroyTexture(g_textureNative);
            g_textureNative = nullptr;
        }

        if (g_renderer) {
            SDL_DestroyRenderer(g_renderer);
            g_renderer = nullptr;
        }

        if (g_window) {
            SDL_DestroyWindow(g_window);
            g_window = nullptr;
        }

        if (g_framebuffer) {
            std::free(g_framebuffer);
            g_framebuffer = nullptr;
        }

        g_argbFramebuffer.clear();
        g_argbFramebuffer.shrink_to_fit();

        g_scaledFramebuffer.clear();
        g_scaledFramebuffer.shrink_to_fit();

        g_initialized = false;
    }

    void SetPixel8(
        int x,
        int y,
        uint8_t colorIndex)
    {
        if (x < 0 ||
            x >= kModeWidth ||
            y < 0 ||
            y >= kModeHeight)
            return;

        if (!EnsureFramebuffer())
            return;

        g_framebuffer[
            static_cast<size_t>(y) *
                kModeWidth + x] =
            colorIndex;
    }

    void SetPaletteEntry(
        uint8_t index,
        uint8_t r,
        uint8_t g,
        uint8_t b)
    {
        g_palette[index] =
            0xFF000000u |
            (static_cast<uint32_t>(r) << 16) |
            (static_cast<uint32_t>(g) << 8) |
            b;
    }

    int GetWindowWidth()
    {
        int w = kModeWidth;
        int h = kModeHeight;

        if (g_window)
            SDL_GetWindowSize(
                g_window,
                &w,
                &h);

        return w > 0
            ? w
            : kModeWidth;
    }

    int GetWindowHeight()
    {
        int w = kModeWidth;
        int h = kModeHeight;

        if (g_window)
            SDL_GetWindowSize(
                g_window,
                &w,
                &h);

        return h > 0
            ? h
            : kModeHeight;
    }

    void Present()
    {
        {
            static int s_on = -1;
            static int s_n = 0;

            if (s_on < 0)
                s_on =
                SDL_getenv(
                    "REORION2_PRESENT_TRACE")
                ? 1
                : 0;

            if (s_on &&
                (s_n++ % 100) == 0) {

                SDL_Log(
                    "PortVga: Present #%d",
                    s_n - 1);
            }
        }

        PortWatchdog_Ping();

        if (!g_initialized ||
            !g_framebuffer)
            return;

        PortDos_ServiceMouse();

        PortSound_ServiceTimer();

        {
            static int s_on = -1;
            static int s_n = 0;

            if (s_on < 0)
                s_on =
                SDL_getenv(
                    "REORION2_PRESENT_TRACE")
                ? 1
                : 0;

            if (s_on &&
                (s_n++ % 200) == 0) {

                size_t nonZeroPixels = 0;

                for (size_t i = 0;
                    i < static_cast<size_t>(
                        kModeWidth) * kModeHeight;
                    ++i) {

                    if (g_framebuffer[i])
                        ++nonZeroPixels;
                }

                int nonBlackPal = 0;

                for (int i = 0;
                    i < 256;
                    ++i) {

                    if ((g_palette[i] &
                        0x00FFFFFFu) != 0)

                        ++nonBlackPal;
                }

                SDL_Log(
                    "PortVga: nenulovych pixelu=%zu z %d, "
                    "necernych barev palety=%d/256",
                    nonZeroPixels,
                    kModeWidth * kModeHeight,
                    nonBlackPal);
            }
        }

        const uint64_t tPresentStart =
            SDL_GetTicksNS();

        uint64_t tAfterConvert = 0;

        // ------------------------------------------------------------
        // 1. Convert palette-indexed VGA framebuffer to ARGB8888.
        // ------------------------------------------------------------

        const size_t sourcePixels =
            static_cast<size_t>(kModeWidth) *
            kModeHeight;

        if (g_argbFramebuffer.size() !=
            sourcePixels) {

            g_argbFramebuffer.resize(
                sourcePixels);
        }

        for (size_t i = 0;
            i < sourcePixels;
            ++i) {

            g_argbFramebuffer[i] =
                g_palette[g_framebuffer[i]];
        }

        tAfterConvert =
            SDL_GetTicksNS();

        // ------------------------------------------------------------
        // 2. Vyber 2x scaleru (viz ScalerKind/ParseScalerKind vyse).
        //    REORION2_SCALER cteno JEDNOU, opravdu ze skutecneho env -
        //    zadny natvrdo zadratovany override.
        // ------------------------------------------------------------

        static ScalerKind s_scaler = ScalerKind::SuperEagle;
        static bool s_scalerRead = false;

        if (!s_scalerRead) {
            s_scalerRead = true;

            const char* env =
                SDL_getenv("REORION2_SCALER");

            s_scaler = ParseScalerKind(env);

            SDL_Log(
                "PortVga: scaler = %s",
                ScalerName(s_scaler));

            // nearest/bilinear obchazeji CPU 2x pass uplne - jen se
            // nahraje nativni 640x480 textura a roztazeni na okno dela
            // GPU (viz krok 3/4 nize). Filtr rozhoduje o vysledku:
            // NEAREST = ostre pixely (zadny "algoritmus" navic neni
            // potreba), LINEAR = jednoduchy bilinear primo pri
            // vykresleni misto rucniho CPU Interpolation2x passu.
            if (s_scaler == ScalerKind::Nearest) {
                SDL_SetTextureScaleMode(
                    g_textureNative,
                    SDL_SCALEMODE_NEAREST);
            } else if (s_scaler == ScalerKind::Bilinear) {
                SDL_SetTextureScaleMode(
                    g_textureNative,
                    SDL_SCALEMODE_LINEAR);
            }
        }

        // REORION2_HQ2XLITE_THRESHOLD - prah pro Hq2xLite (RGB per-kanal,
        // viz scalers2x.h). Cteno jen jednou, default 24.
        static int s_hq2xLiteThreshold = -1;

        if (s_hq2xLiteThreshold < 0) {
            const char* env =
                SDL_getenv("REORION2_HQ2XLITE_THRESHOLD");

            s_hq2xLiteThreshold =
                env ? SDL_atoi(env) : 24;

            if (s_hq2xLiteThreshold < 0)
                s_hq2xLiteThreshold = 0;
            if (s_hq2xLiteThreshold > 255)
                s_hq2xLiteThreshold = 255;

            if (s_scaler == ScalerKind::Hq2xLite) {
                SDL_Log(
                    "PortVga: hq2xlite threshold = %d",
                    s_hq2xLiteThreshold);
            }
        }

        // REORION2_HQ2XFULL_{Y,U,V}_THRESHOLD - oddelene prahy pro
        // Hq2xFull (jas/barva, viz scalers2x.h). Cteno jen jednou,
        // default 48/7/6.
        static int s_hq2xFullY = -1;
        static int s_hq2xFullU = -1;
        static int s_hq2xFullV = -1;

        if (s_hq2xFullY < 0) {
            const char* envY =
                SDL_getenv("REORION2_HQ2XFULL_Y_THRESHOLD");
            const char* envU =
                SDL_getenv("REORION2_HQ2XFULL_U_THRESHOLD");
            const char* envV =
                SDL_getenv("REORION2_HQ2XFULL_V_THRESHOLD");

            s_hq2xFullY = envY ? SDL_atoi(envY) : 48;
            s_hq2xFullU = envU ? SDL_atoi(envU) : 7;
            s_hq2xFullV = envV ? SDL_atoi(envV) : 6;

            if (s_hq2xFullY < 0) s_hq2xFullY = 0;
            if (s_hq2xFullU < 0) s_hq2xFullU = 0;
            if (s_hq2xFullV < 0) s_hq2xFullV = 0;

            if (s_scaler == ScalerKind::Hq2xFull) {
                SDL_Log(
                    "PortVga: hq2xfull thresholds = Y%d U%d V%d",
                    s_hq2xFullY,
                    s_hq2xFullU,
                    s_hq2xFullV);
            }
        }

        // ------------------------------------------------------------
        // 3. Nahrat obraz do SDL textury.
        //
        //    nearest/bilinear: zadny CPU 2x pass - primo se nahraje
        //    nativni 640x480 textura, roztazeni na velikost okna dela
        //    GPU podle scale mode nastaveneho vyse (NEAREST/LINEAR).
        //
        //    ostatni: CPU 2x algoritmus (viz ScalerKind) vyrobi 1280x960
        //    obraz do g_scaledFramebuffer, ten se nahraje do g_texture.
        // ------------------------------------------------------------

        SDL_Texture* activeTexture = nullptr;

        if (s_scaler == ScalerKind::Nearest ||
            s_scaler == ScalerKind::Bilinear) {

            SDL_UpdateTexture(
                g_textureNative,
                nullptr,
                g_argbFramebuffer.data(),
                static_cast<int>(
                    kModeWidth * sizeof(uint32_t)));

            activeTexture = g_textureNative;

        } else {

            const size_t scaledPixels =
                static_cast<size_t>(kModeWidth * 2) *
                (kModeHeight * 2);

            if (g_scaledFramebuffer.size() !=
                scaledPixels) {

                g_scaledFramebuffer.resize(
                    scaledPixels);
            }

            switch (s_scaler) {
            case ScalerKind::Scale2x:
                Scalers2x::AdvMame2x(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2);
                break;

            case ScalerKind::Sai2x:
                Scalers2x::SAI2x(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2);
                break;

            case ScalerKind::Super2xSai:
                Scalers2x::Super2xSaI(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2);
                break;

            case ScalerKind::Hq2xLite:
                Scalers2x::Hq2xLite(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2,
                    s_hq2xLiteThreshold);
                break;

            case ScalerKind::Hq2xFull:
                Scalers2x::Hq2xFull(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2,
                    s_hq2xFullY,
                    s_hq2xFullU,
                    s_hq2xFullV);
                break;

            case ScalerKind::Scale2xSmooth:
                Scalers2x::Scale2xSmooth(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2,
                    kScale2xSmoothThreshold);
                break;

            case ScalerKind::Nearest:
            case ScalerKind::Bilinear:
                // Nedosazitelne - resi se vyse pred timto switchem.
                break;

            case ScalerKind::SuperEagle:
            default:
                Scalers2x::SuperEagle2x(
                    g_argbFramebuffer.data(),
                    kModeWidth,
                    kModeHeight,
                    g_scaledFramebuffer.data(),
                    kModeWidth * 2);
                break;
            }

            void* pixels = nullptr;
            int pitch = 0;

            if (SDL_LockTexture(
                g_texture,
                nullptr,
                &pixels,
                &pitch)) {

                const size_t rowBytes =
                    static_cast<size_t>(
                        kModeWidth * 2) *
                    sizeof(uint32_t);

                const size_t dstPitch =
                    static_cast<size_t>(pitch);

                const uint8_t* srcBytes =
                    reinterpret_cast<const uint8_t*>(
                        g_scaledFramebuffer.data());

                uint8_t* dstBytes =
                    reinterpret_cast<uint8_t*>(
                        pixels);

                for (int y = 0;
                    y < kModeHeight * 2;
                    ++y) {

                    std::memcpy(
                        dstBytes +
                        static_cast<size_t>(y) *
                        dstPitch,

                        srcBytes +
                        static_cast<size_t>(y) *
                        rowBytes,

                        rowBytes);
                }

                SDL_UnlockTexture(
                    g_texture);
            }

            activeTexture = g_texture;
        }

        DumpFrameIfRequested(
            g_framebuffer,
            g_palette,
            kModeWidth,
            kModeHeight);

        CompareAgainstReferenceIfChanged(
            g_framebuffer,
            g_palette,
            kModeWidth,
            kModeHeight);

        // ------------------------------------------------------------
        // 5. Present.
        // ------------------------------------------------------------

        SDL_RenderClear(
            g_renderer);

        SDL_RenderTexture(
            g_renderer,
            activeTexture,
            nullptr,
            nullptr);

        SDL_RenderPresent(
            g_renderer);

        {
            static int s_on = -1;

            if (s_on < 0)
                s_on =
                SDL_getenv(
                    "REORION2_PRESENT_TRACE")
                ? 1
                : 0;

            if (s_on) {
                static uint64_t sumConvert = 0;
                static uint64_t sumRest = 0;
                static int n = 0;

                const uint64_t tEnd =
                    SDL_GetTicksNS();

                sumConvert +=
                    tAfterConvert -
                    tPresentStart;

                sumRest +=
                    tEnd -
                    tAfterConvert;

                if (++n % 100 == 0) {
                    SDL_Log(
                        "PortVga: Present prumer - "
                        "prevod palety %.2f ms, "
                        "zbytek %.2f ms",
                        static_cast<double>(
                            sumConvert) /
                        n /
                        1e6,

                        static_cast<double>(
                            sumRest) /
                        n /
                        1e6);
                }
            }
        }
    }

} // namespace Port::Vga

// ---------------------------------------------------------------------
// C-linkage most pro dekompilovany herni kod (vlna 13).
extern "C" {

    unsigned char* PortVga_Framebuffer(void)
    {
        return Port::Vga::Framebuffer();
    }

    static int g_videoWindowBank = 0;

    void PortVga_SetVideoWindow(int bank)
    {
        g_videoWindowBank =
            ((bank % 5) + 5) % 5;
    }

    unsigned char* PortVga_VideoWindow(void)
    {
        unsigned char* base =
            Port::Vga::Framebuffer();

        return base
            ? base +
            (size_t)g_videoWindowBank *
            0x10000u
            : base;
    }

    static void PortVga_WaitSliced(
        uint32_t totalMs)
    {
        const uint64_t end =
            SDL_GetTicks() +
            totalMs;

        for (;;) {
            Port::Vga::Present();

            const uint64_t now =
                SDL_GetTicks();

            if (now >= end)
                break;

            const uint64_t left =
                end - now;

            SDL_Delay(
                static_cast<uint32_t>(
                    left > 8 ? 8 : left));
        }
    }

    void PortVga_WaitVsync(void)
    {
        PortVga_WaitSliced(14);
    }

    void PortVga_BlitBackBuffer(
        const void* backBuffer)
    {
        if (!backBuffer ||
            !Port::Vga::g_framebuffer)
            return;

        std::memcpy(
            Port::Vga::g_framebuffer,
            backBuffer,
            static_cast<size_t>(
                Port::Vga::kModeWidth) *
            Port::Vga::kModeHeight);

        Port::Vga::Present();

        PortSound_ServiceTimer();
    }

    void PortVga_CaptureBlit(
        const void* backBuffer)
    {
        Port::Memory::CheckGuards(
            "blit");

        static bool s_checked = false;
        static std::string s_dir;
        static int s_written = 0;
        static int s_max = 0;

        static std::vector<uint8_t> s_lastFb;
        static std::array<uint32_t, 256> s_lastPal{};

        static bool s_havePrev = false;

        if (!s_checked) {
            s_checked = true;

            if (const char* env =
                std::getenv(
                    "REORION2_BLIT_DUMP_DIR")) {

                s_dir = env;
                s_max = 600;

                if (const char* cnt =
                    std::getenv(
                        "REORION2_BLIT_DUMP_COUNT")) {

                    s_max =
                        std::atoi(cnt);
                }

                SDL_Log(
                    "Port::Vga: "
                    "blit-triggered dump to %s "
                    "(max %d frames)",
                    s_dir.c_str(),
                    s_max);
            }
        }

        if (s_dir.empty() ||
            s_written >= s_max)
            return;

        const uint8_t* fb =
            static_cast<const uint8_t*>(
                backBuffer);

        if (!fb)
            return;

        const int w =
            Port::Vga::kModeWidth;

        const int h =
            Port::Vga::kModeHeight;

        size_t fbBytes =
            static_cast<size_t>(w) * h;

        const std::array<uint32_t, 256>& pal =
            Port::Vga::g_palette;

        bool changed =
            !s_havePrev ||
            s_lastFb.size() != fbBytes ||
            std::memcmp(
                s_lastFb.data(),
                fb,
                fbBytes) != 0 ||
            s_lastPal != pal;

        if (!changed)
            return;

        char name[64];

        std::snprintf(
            name,
            sizeof(name),
            "/frame_%05d.raw",
            s_written);

        Port::Vga::DumpRawFrame(
            s_dir + name,
            fb,
            pal,
            w,
            h);

        s_lastFb.assign(
            fb,
            fb + fbBytes);

        s_lastPal = pal;
        s_havePrev = true;

        ++s_written;
    }

    void PortVga_WaitVsyncSlow(void)
    {
        PortVga_WaitSliced(50);
    }

    void PortVga_SetPaletteEntry(
        int index,
        int r,
        int g,
        int b)
    {
        Port::Vga::SetPaletteEntry(
            static_cast<uint8_t>(index),
            static_cast<uint8_t>(r),
            static_cast<uint8_t>(g),
            static_cast<uint8_t>(b));
    }

} // extern "C"
